### ISSUE TITLE
Make videos play when hovering on it.

### ISSUE THREAD

**Issue by vishal-k25** [vishal-k25/YoutubeClone#1]

**Comment by Pratik-005** [comment]
Hello Vishal ,
I'd like to contribute and work with you to find the solution of the issue that you are facing . Please let me know your thoughts on this. Looking forward to your response.

**Comment by Pratik-0007** [comment]
Hello Vishal , I'd like to contribute and work with you to find the solution of the issue that you are facing . Please let me know your thoughts on this. Looking forward to your response.

**Comment by vishal-k25** [comment]
Successfully working hovering functionality.
